//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4216
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTest.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegexTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   /left:&quot;{0}&quot; /right:&quot;{1}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TortoiseIDiffFormat {
            get {
                return ResourceManager.GetString("TortoiseIDiffFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C:\Program Files\TortoiseSVN\bin\TortoiseIDiff.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TortoiseIDiffPath {
            get {
                return ResourceManager.GetString("TortoiseIDiffPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /base:&quot;{0}&quot; /mine:&quot;{1}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TortoiseMergeFormat {
            get {
                return ResourceManager.GetString("TortoiseMergeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C:\Program Files\TortoisesSVN\bin\TortoiseMerge.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TortoiseMergePath {
            get {
                return ResourceManager.GetString("TortoiseMergePath", resourceCulture);
            }
        }
    }
}
